In [10]:
import torch
A_log = torch.arange(1, 7, dtype=torch.float32).repeat(3, 1)
A_log

tensor([[1., 2., 3., 4., 5., 6.],
        [1., 2., 3., 4., 5., 6.],
        [1., 2., 3., 4., 5., 6.]])

In [11]:
-torch.exp(A_log)

tensor([[  -2.7183,   -7.3891,  -20.0855,  -54.5981, -148.4132, -403.4288],
        [  -2.7183,   -7.3891,  -20.0855,  -54.5981, -148.4132, -403.4288],
        [  -2.7183,   -7.3891,  -20.0855,  -54.5981, -148.4132, -403.4288]])

In [17]:
import torch
A = torch.randn(1,3,8,5)
A.shape, A
# A.view(B, D, T//2, 2, -1)

(torch.Size([1, 3, 8, 5]),
 tensor([[[[ 0.0149,  1.0620,  0.6860,  1.6200,  0.3817],
           [-2.0105, -0.0560,  1.6777, -0.4162,  0.0280],
           [-0.7061,  0.9497, -0.5578, -0.6671, -1.9334],
           [ 0.5835,  0.6507,  2.4012, -0.5278,  0.9189],
           [-0.7883,  0.1590,  0.1658,  1.3018, -1.9521],
           [-1.4522,  0.8056, -1.4679,  0.0766, -0.4815],
           [ 1.3146,  1.1042, -1.9432,  1.3357, -0.4656],
           [ 0.6693,  1.2127, -0.6903,  0.8093,  1.4694]],
 
          [[ 0.5412,  0.5469, -0.1929, -1.2515, -0.0939],
           [ 1.1017,  0.3846,  0.2337, -0.2533,  1.0348],
           [-0.3566, -1.3161,  0.3550,  1.3334, -0.4789],
           [ 0.2777, -1.5053,  1.2255, -0.6829,  1.1664],
           [-2.2655,  1.6950, -0.1992,  0.1106, -1.2183],
           [-0.0915, -0.9948,  0.0468,  1.3694,  1.6693],
           [-1.0273,  1.6018,  0.6709,  0.7325, -0.5703],
           [ 0.9582,  0.0840,  0.7547, -0.1533,  0.6270]],
 
          [[ 0.5508,  0.4332,  0.9936, 

In [18]:
A.view(1, 3, 4, 2, -1).shape

torch.Size([1, 3, 4, 2, 5])

In [27]:
torch.range(1,100)[1:10:30]

/tmp/ipykernel_275519/326531738.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,100)[1:10:30]


tensor([2.])