In [1]:
from c66 import pps
import torch
x = torch.randn(2,5,1)
y = torch.randn(3,)
pps(x,y)

x's shape: torch.Size([2, 5, 1])
y's shape: torch.Size([3])


In [2]:
import torch
from mambapy.mamba import Mamba, MambaConfig
from torchinfo import summary
from c66 import pp

# B, L, D = 7, 64, 16
B, L, D = 7, 286, 64
pp(B,L,D)

config = MambaConfig(d_model=D, n_layers=1, use_cuda=False)
model = Mamba(config)

B: 7
L: 286
D: 64


In [3]:
model.layers[0].mixer.A_log

Parameter containing:
tensor([[0.0000, 0.6931, 1.0986,  ..., 2.6391, 2.7081, 2.7726],
        [0.0000, 0.6931, 1.0986,  ..., 2.6391, 2.7081, 2.7726],
        [0.0000, 0.6931, 1.0986,  ..., 2.6391, 2.7081, 2.7726],
        ...,
        [0.0000, 0.6931, 1.0986,  ..., 2.6391, 2.7081, 2.7726],
        [0.0000, 0.6931, 1.0986,  ..., 2.6391, 2.7081, 2.7726],
        [0.0000, 0.6931, 1.0986,  ..., 2.6391, 2.7081, 2.7726]],
       requires_grad=True)

In [4]:
model.layers[0].mixer.D

Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.], requires_grad=True)

In [5]:
import torch
from mambapy.mamba import Mamba, MambaConfig, MambaBlock
from torchinfo import summary
from c66 import pp

# B, L, D = 7, 64, 16
B, L, D = 7, 286, 64
pp(B,L,D)

config = MambaConfig(d_model=D, n_layers=1, use_cuda=False)
model = Mamba(config)
# .to("cuda")

x = torch.randn(B, L, D)
# .to("cuda")
y = model(x)

assert y.shape == x.shape
pp(x.shape)

B: 7
L: 286
D: 64
------------------------------
In ResidualBlock
x.shape: torch.Size([7, 286, 64])
self.norm(x).shape: torch.Size([7, 286, 64])
------------------------------
------------------------------
In MambaBlock
B, L, ED, N, dt_rank: 7 286 128 16 4
x.shape: torch.Size([7, 286, 128])
delta.shape: torch.Size([7, 286, 128])
A.shape: torch.Size([128, 16])
B.shape: torch.Size([7, 286, 16])
C.shape: torch.Size([7, 286, 16])
z.shape: torch.Size([7, 286, 128])
self.selective_scan
最初的X
X's shape: torch.Size([7, 128, 512, 16])
X[0, 0, :3, :3]: tensor([[-6.6600e-06, -4.9130e-05, -2.5699e-05],
        [-2.3167e-05,  7.0279e-05, -1.2622e-05],
        [-2.7348e-04, -2.3712e-04,  7.8647e-05]])
X.abs().mean(): 0.00018666102550923824
B: 7
D: 128
L: 512
N: 16
up sweep finish.
中間的X
Xa's shape: torch.Size([7, 128, 4, 16])
X's shape: torch.Size([7, 128, 512, 16])
X[0, 0, :3, :3]: tensor([[-6.6600e-06, -4.9130e-05, -2.5699e-05],
        [-2.9764e-05,  2.2072e-05, -3.7600e-05],
        [-2.7348e-04,

In [6]:
num_steps = 6
print(torch.arange(1,2**num_steps+1))
for k in range(num_steps-3,-1,-1):
    print(k)
    print(torch.arange(1,2**num_steps+1)[2**k-1:2**num_steps:2**k])

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60, 61, 62, 63, 64])
3
tensor([ 8, 16, 24, 32, 40, 48, 56, 64])
2
tensor([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64])
1
tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
        38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64])
0
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60, 61, 62, 63, 64])


In [7]:
print(model.layers[0].mixer)

MambaBlock(
  (in_proj): Linear(in_features=64, out_features=256, bias=False)
  (conv1d): Conv1d(128, 128, kernel_size=(4,), stride=(1,), padding=(3,), groups=128)
  (x_proj): Linear(in_features=128, out_features=36, bias=False)
  (dt_proj): Linear(in_features=4, out_features=128, bias=True)
  (out_proj): Linear(in_features=128, out_features=64, bias=False)
)


## MambaBlock

In [8]:
D = 64

In [9]:
# model_mamba = model.layers[0].mixer
from mambapy.mamba import Mamba, MambaConfig, MambaBlock
config = MambaConfig(d_model=D, n_layers=1, use_cuda=False, 
                     expand_factor=4,
                     )
model_mamba = MambaBlock(config)

In [10]:
model_mamba.conv1d.weight

Parameter containing:
tensor([[[ 0.2850,  0.1104,  0.4010,  0.0377]],

        [[ 0.1681, -0.2200,  0.1277, -0.2068]],

        [[ 0.1601, -0.1528,  0.1214,  0.0539]],

        ...,

        [[-0.1568,  0.2847,  0.2409, -0.0708]],

        [[-0.3168, -0.3974,  0.3912, -0.2257]],

        [[ 0.4370, -0.4213,  0.4236,  0.0247]]], requires_grad=True)

In [11]:
import torch
from torchinfo import summary
(B,L,D) = (1, 286, 64)
with torch.no_grad():
    summary_str = summary(model_mamba, input_size=[(B,L,D)], depth=5, col_names=("input_size", "output_size", "num_params"), verbose=0)
    print(summary_str)

------------------------------
In MambaBlock
B, L, ED, N, dt_rank: 1 286 256 16 4
x.shape: torch.Size([1, 286, 256])
delta.shape: torch.Size([1, 286, 256])
A.shape: torch.Size([256, 16])
B.shape: torch.Size([1, 286, 16])
C.shape: torch.Size([1, 286, 16])
z.shape: torch.Size([1, 286, 256])
self.selective_scan
最初的X
X's shape: torch.Size([1, 256, 512, 16])
X[0, 0, :3, :3]: tensor([[-1.1290e-04,  5.8376e-04,  1.7332e-04],
        [-7.2843e-04,  1.2419e-03,  8.3333e-04],
        [ 8.0439e-05,  5.5910e-04,  7.8813e-04]], device='cuda:0')
X.abs().mean(): 0.00013546888658311218
B: 1
D: 256
L: 512
N: 16
up sweep finish.
中間的X
Xa's shape: torch.Size([1, 256, 4, 16])
X's shape: torch.Size([1, 256, 512, 16])
X[0, 0, :3, :3]: tensor([[-1.1290e-04,  5.8376e-04,  1.7332e-04],
        [-8.3808e-04,  1.7925e-03,  9.9209e-04],
        [ 8.0439e-05,  5.5910e-04,  7.8813e-04]], device='cuda:0')
X.abs().mean(): 0.00024662743089720607
down sweep begin
Xa's shape: torch.Size([1, 256, 256, 2, 16])
結束的X
X's sha

In [12]:
input_x = torch.randn(1,286,64)
# input_x = torch.randn(500,286,64)

from calflops import calculate_flops
with torch.no_grad():
        # 使用 calflops 計算 FLOPs，將 args 改為列表
        flops, macs, params = calculate_flops(
            model=model_mamba,
            args=[input_x],  # 使用列表而非元組
            print_results=True  # 顯示逐層結果
        )
        # print(f"Total FLOPs for {fname}: {flops / 1e9:.3f} GFLOPs")
        # print(f"Total Params: {params / 1e6:.3f} M")
        # print(f"Total MACs: {macs / 1e9:.3f} GMACs")
        print(f"Total FLOPs: {flops}")
        print(f"Total Params: {params}")
        print(f"Total MACs: {macs}")

------------------------------
In MambaBlock
B, L, ED, N, dt_rank: 1 286 256 16 4
x.shape: torch.Size([1, 286, 256])
delta.shape: torch.Size([1, 286, 256])
A.shape: torch.Size([256, 16])
B.shape: torch.Size([1, 286, 16])
C.shape: torch.Size([1, 286, 16])
z.shape: torch.Size([1, 286, 256])
self.selective_scan
最初的X
X's shape: torch.Size([1, 256, 512, 16])
X[0, 0, :3, :3]: tensor([[-1.9654e-05,  2.5319e-04, -1.8540e-04],
        [ 6.6260e-05,  8.9256e-06,  8.0261e-05],
        [ 1.3902e-04,  1.3509e-03,  5.0110e-04]], device='cuda:0')
X.abs().mean(): 0.00018443376757204533
B: 1
D: 256
L: 512
N: 16
up sweep finish.
中間的X
Xa's shape: torch.Size([1, 256, 4, 16])
X's shape: torch.Size([1, 256, 512, 16])
X[0, 0, :3, :3]: tensor([[-1.9654e-05,  2.5319e-04, -1.8540e-04],
        [ 4.7149e-05,  2.4830e-04, -9.0170e-05],
        [ 1.3902e-04,  1.3509e-03,  5.0110e-04]], device='cuda:0')
X.abs().mean(): 0.0002665412030182779
down sweep begin
Xa's shape: torch.Size([1, 256, 256, 2, 16])
結束的X
X's shap