In [1]:
from c66 import pps
import torch
x = torch.randn(2,5,1)
y = torch.randn(3,)
pps(x,y)

x's shape: torch.Size([2, 5, 1])
y's shape: torch.Size([3])


In [2]:
import torch
from mambapy.mamba import Mamba, MambaConfig
from torchinfo import summary
from c66 import pp

# B, L, D = 7, 64, 16
B, L, D = 7, 286, 64
pp(B,L,D)

config = MambaConfig(d_model=D, n_layers=1, use_cuda=False)
model = Mamba(config)

B: 7
L: 286
D: 64


In [3]:
model.layers[0].mixer.A_log

Parameter containing:
tensor([[0.0000, 0.6931, 1.0986,  ..., 2.6391, 2.7081, 2.7726],
        [0.0000, 0.6931, 1.0986,  ..., 2.6391, 2.7081, 2.7726],
        [0.0000, 0.6931, 1.0986,  ..., 2.6391, 2.7081, 2.7726],
        ...,
        [0.0000, 0.6931, 1.0986,  ..., 2.6391, 2.7081, 2.7726],
        [0.0000, 0.6931, 1.0986,  ..., 2.6391, 2.7081, 2.7726],
        [0.0000, 0.6931, 1.0986,  ..., 2.6391, 2.7081, 2.7726]],
       requires_grad=True)

In [4]:
model.layers[0].mixer.D

Parameter containing:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1.], requires_grad=True)

In [5]:
import torch
from mambapy.mamba import Mamba, MambaConfig, MambaBlock
from torchinfo import summary
from c66 import pp

# B, L, D = 7, 64, 16
B, L, D = 7, 286, 64
pp(B,L,D)

config = MambaConfig(d_model=D, n_layers=1, use_cuda=False)
model = Mamba(config)
# .to("cuda")

x = torch.randn(B, L, D)
# .to("cuda")
y = model(x)

assert y.shape == x.shape
pp(x.shape)

B: 7
L: 286
D: 64
------------------------------
In ResidualBlock
x.shape: torch.Size([7, 286, 64])
self.norm(x).shape: torch.Size([7, 286, 64])
------------------------------
------------------------------
In MambaBlock
B, L, ED, N, dt_rank: 7 286 128 16 4
x.shape: torch.Size([7, 286, 128])
delta.shape: torch.Size([7, 286, 128])
A.shape: torch.Size([128, 16])
B.shape: torch.Size([7, 286, 16])
C.shape: torch.Size([7, 286, 16])
z.shape: torch.Size([7, 286, 128])
self.selective_scan
最初的X
X's shape: torch.Size([7, 128, 512, 16])
X[0, 0, :3, :3]: tensor([[ 4.6876e-05,  6.9070e-06,  2.0421e-05],
        [ 2.1344e-05, -3.1894e-06,  1.0125e-04],
        [ 6.1279e-06,  1.6529e-05,  3.4905e-05]])
X.abs().mean(): 0.0002599538129288703
B: 7
D: 128
L: 512
N: 16
up sweep finish.
中間的X
Xa's shape: torch.Size([7, 128, 4, 16])
X's shape: torch.Size([7, 128, 512, 16])
X[0, 0, :3, :3]: tensor([[4.6876e-05, 6.9070e-06, 2.0421e-05],
        [6.8087e-05, 3.6785e-06, 1.2150e-04],
        [6.1279e-06, 1.6529e

In [21]:
num_steps = 6
print(torch.arange(1,2**num_steps+1))
for k in range(num_steps-3,-1,-1):
    print(k)
    print(torch.arange(1,2**num_steps+1)[2**k-1:2**num_steps:2**k])

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60, 61, 62, 63, 64])
3
tensor([ 8, 16, 24, 32, 40, 48, 56, 64])
2
tensor([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64])
1
tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
        38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64])
0
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60, 61, 62, 63, 64])


In [ ]:
print(model.layers[0].mixer)

MambaBlock(
  (in_proj): Linear(in_features=64, out_features=256, bias=False)
  (conv1d): Conv1d(128, 128, kernel_size=(4,), stride=(1,), padding=(3,), groups=128)
  (x_proj): Linear(in_features=128, out_features=36, bias=False)
  (dt_proj): Linear(in_features=4, out_features=128, bias=True)
  (out_proj): Linear(in_features=128, out_features=64, bias=False)
)


## MambaBlock

In [ ]:
# model_mamba = model.layers[0].mixer
from mambapy.mamba import Mamba, MambaConfig, MambaBlock
config = MambaConfig(d_model=D, n_layers=1, use_cuda=False, 
                     expand_factor=4,
                     )
model_mamba = MambaBlock(config)

In [ ]:
(B,L,D) = (100, 286, 64)
with torch.no_grad():
    summary_str = summary(model_mamba, input_size=[(B,L,D)], depth=5, col_names=("input_size", "output_size", "num_params"), verbose=0)
    print(summary_str)

------------------------------
In MambaBlock
B, L, ED, N, dt_rank: 100 286 256 16 4
x.shape: torch.Size([100, 286, 256])
delta.shape: torch.Size([100, 286, 256])
A.shape: torch.Size([256, 16])
B.shape: torch.Size([100, 286, 16])
C.shape: torch.Size([100, 286, 16])
z.shape: torch.Size([100, 286, 256])
self.selective_scan
-------
tensor([ 2.4182e-06,  1.9445e-05, -4.6299e-06], device='cuda:0')
B: 100
D: 256
L: 512
N: 16
把 Aa, Xa 分成兩塊
Xa's shape: torch.Size([100, 256, 256, 2, 16])
把 Aa[:, :, :, 1], Xa[:, :, :, 1] 當成新的 Aa, Xa
Xa's shape: torch.Size([100, 256, 256, 16])
把 Aa, Xa 分成兩塊
Xa's shape: torch.Size([100, 256, 128, 2, 16])
把 Aa[:, :, :, 1], Xa[:, :, :, 1] 當成新的 Aa, Xa
Xa's shape: torch.Size([100, 256, 128, 16])
把 Aa, Xa 分成兩塊
Xa's shape: torch.Size([100, 256, 64, 2, 16])
把 Aa[:, :, :, 1], Xa[:, :, :, 1] 當成新的 Aa, Xa
Xa's shape: torch.Size([100, 256, 64, 16])
把 Aa, Xa 分成兩塊
Xa's shape: torch.Size([100, 256, 32, 2, 16])
把 Aa[:, :, :, 1], Xa[:, :, :, 1] 當成新的 Aa, Xa
Xa's shape: torch.Size([1

In [9]:
input_x = torch.randn(100,286,64)
# input_x = torch.randn(500,286,64)

from calflops import calculate_flops
with torch.no_grad():
        # 使用 calflops 計算 FLOPs，將 args 改為列表
        flops, macs, params = calculate_flops(
            model=model_mamba,
            args=[input_x],  # 使用列表而非元組
            print_results=True  # 顯示逐層結果
        )
        # print(f"Total FLOPs for {fname}: {flops / 1e9:.3f} GFLOPs")
        # print(f"Total Params: {params / 1e6:.3f} M")
        # print(f"Total MACs: {macs / 1e9:.3f} GMACs")
        print(f"Total FLOPs: {flops}")
        print(f"Total Params: {params}")
        print(f"Total MACs: {macs}")

------------------------------
In MambaBlock
B, L, ED, N, dt_rank: 100 286 256 16 4
x.shape: torch.Size([100, 286, 256])
delta.shape: torch.Size([100, 286, 256])
A.shape: torch.Size([256, 16])
B.shape: torch.Size([100, 286, 16])
C.shape: torch.Size([100, 286, 16])
z.shape: torch.Size([100, 286, 256])
self.selective_scan
-------
tensor([-1.1309e-06, -2.4537e-07,  7.4916e-07], device='cuda:0')
B: 100
D: 256
L: 512
N: 16
把 Aa, Xa 分成兩塊
Xa's shape: torch.Size([100, 256, 256, 2, 16])
把 Aa[:, :, :, 1], Xa[:, :, :, 1] 當成新的 Aa, Xa
Xa's shape: torch.Size([100, 256, 256, 16])
把 Aa, Xa 分成兩塊
Xa's shape: torch.Size([100, 256, 128, 2, 16])
把 Aa[:, :, :, 1], Xa[:, :, :, 1] 當成新的 Aa, Xa
Xa's shape: torch.Size([100, 256, 128, 16])
把 Aa, Xa 分成兩塊
Xa's shape: torch.Size([100, 256, 64, 2, 16])
把 Aa[:, :, :, 1], Xa[:, :, :, 1] 當成新的 Aa, Xa
Xa's shape: torch.Size([100, 256, 64, 16])
把 Aa, Xa 分成兩塊
Xa's shape: torch.Size([100, 256, 32, 2, 16])
把 Aa[:, :, :, 1], Xa[:, :, :, 1] 當成新的 Aa, Xa
Xa's shape: torch.Size([1