In [18]:
import torch
torch.tensor([1, 2, 3]).repeat(2, 1, 5)

tensor([[[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]],

        [[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]]])

In [27]:
torch.arange(1,5).shape

torch.Size([4])

In [24]:
import torch
d_state = 3
d_inner = 5
A = torch.arange(1, d_state + 1, dtype=torch.float32).repeat(d_inner, 1)
print(A)
A.shape

tensor([[1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.],
        [1., 2., 3.]])


torch.Size([5, 3])

In [7]:
import torch
d_state = 3
d_inner = 5
A = torch.arange(1, d_state + 1, dtype=torch.float32).repeat(d_inner, 0)
print(A)
A.shape

tensor([], size=(5, 0))


torch.Size([5, 0])

In [8]:
import torch
d_state = 3
d_inner = 5
A = torch.arange(1, d_state + 1, dtype=torch.float32).repeat(d_inner, 2)
print(A)
A.shape

tensor([[1., 2., 3., 1., 2., 3.],
        [1., 2., 3., 1., 2., 3.],
        [1., 2., 3., 1., 2., 3.],
        [1., 2., 3., 1., 2., 3.],
        [1., 2., 3., 1., 2., 3.]])


torch.Size([5, 6])